# @package hydra.launcher
# SLURM Cluster Execution Configuration

_target_: hydra_plugins.hydra_submitit_launcher.submitit_launcher.SlurmLauncher

partition: gpu
nodes: 1
tasks_per_node: 1
cpus_per_task: 4
mem_gb: 32
time: 60  # minutes
gpu: 1

# SLURM additional settings
additional_parameters:
  constraint: "gpu"
  exclude: ""
  
# Hydra specific
max_num_timeout: 3