seed: 42
environment:
  num_variables: 8
  edge_density: 0.3
  noise_scale: 0.1
  target_variable_idx: 0
training:
  max_training_steps: 2000
  algorithm:
    learning_rate: 0.0003
    batch_size: 32
    enhanced_architecture_level: full
    enhanced_performance_mode: balanced
    use_enhanced_networks: true
  surrogate:
    model_complexity: full
    use_continuous: true
  curriculum:
    enabled: false
  rewards:
    use_verifiable_rewards: true
    target_improvement_weight: 2.0
    true_parent_weight: 1.0
    exploration_weight: 0.5
  logging:
    enable_wandb: false
    wandb:
      project: enhanced_acbo_training
      tags:
      - enhanced
      - acbo
      - grpo
