# @package _global_
# Baseline Model Architecture Configuration

training:
  architecture:
    level: "baseline"
    performance_mode: "fast"
    use_enhanced_networks: false
    
model:
  architecture_level: "baseline"
  performance_mode: "fast"
  
  # Baseline network settings
  baseline:
    use_simple_networks: true
    use_standard_attention: true
    
  # Network dimensions (smaller for baseline)
  dimensions:
    hidden_dim: 128
    n_layers: 2
    attention_heads: 4
    
  # Optimization (simpler for baseline)
  optimization:
    use_jax_compilation: false
    enable_gradient_clipping: true
    clip_value: 1.0