[project]
name = "causal-bayes-opt"
version = "0.1.0"
description = ""
authors = [
    {name = "Harel",email = "hl1824@ic.ac.uk"}
]
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pyrsistent (>=0.20.0,<0.21.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
