# @package logging
# Local development logging (no external services)

wandb:
  enabled: false

console:
  level: DEBUG
  frequency: 5

tensorboard:
  enabled: true

metrics:
  log_gradients: true
  log_weights: true
  log_activations: false
