# @package logging
# WandB enabled logging configuration

wandb:
  enabled: true
  project: "causal_bayes_opt"
  entity: null  # Use default
  tags: ["hydra", "acbo"]
  group: "experiment"

console:
  level: INFO
  frequency: 10

tensorboard:
  enabled: false

metrics:
  log_gradients: false
  log_weights: false
  log_activations: false
