# Debug Configuration for Behavioral Cloning Training
# Fast configuration for testing and debugging

# @package _global_
defaults:
  - behavioral_cloning

# Override data settings for faster debugging
data:
  max_examples_per_demo: 10  # Limit examples per demo

# Override training settings for faster runs
training:
  surrogate:
    batch_size: 8
    max_epochs_per_level: 5
    min_epochs_per_level: 2
    validation_patience: 3
  
  acquisition:
    batch_size: 16
    max_epochs_per_level: 3
    min_epochs_per_level: 1
    validation_patience: 2

# Override validation for faster testing
validation:
  max_test_trajectories: 5

# Override models for smaller/faster architectures
models:
  surrogate:
    hidden_dims: [64, 32]
    dropout_rate: 0.0
  
  acquisition:
    hidden_dims: [32, 16]
    dropout_rate: 0.0

# Override logging for debug
logging:
  level: "DEBUG"
  use_wandb: false  # Disable wandb for debug runs
  run_name: "debug_${now:%H%M%S}"

# Override output
output:
  results_directory: "results/debug"
  save_checkpoints: false