# Behavioral Cloning Training Configuration
# Main configuration file for training both surrogate and acquisition models
# using expert demonstrations with curriculum learning

# Data configuration
data:
  demo_directory: "expert_demonstrations/raw/raw_demonstrations"
  split_ratios: [0.7, 0.15, 0.15]  # train, validation, test
  max_examples_per_demo: null  # null for no limit

# Training configuration
training:
  # General settings
  random_seed: 42
  use_curriculum: true
  use_jax_compilation: true
  
  # Surrogate model training
  surrogate:
    learning_rate: 1e-3
    batch_size: 32
    max_epochs_per_level: 100
    min_epochs_per_level: 10
    advancement_threshold: 0.1  # KL divergence threshold
    validation_patience: 10
  
  # Acquisition model training
  acquisition:
    learning_rate: 1e-3
    batch_size: 64
    max_epochs_per_level: 50
    min_epochs_per_level: 5
    advancement_threshold: 0.8  # Accuracy threshold
    validation_patience: 10
  
  # Curriculum learning
  curriculum:
    start_difficulty: "EASY"  # EASY, MEDIUM, HARD, EXPERT
    difficulty_weights:
      graph_complexity: 0.3
      convergence_difficulty: 0.2
      posterior_uncertainty: 0.2
      intervention_complexity: 0.3

# Validation configuration
validation:
  top_k: 5  # Top-k parent sets for comparison
  max_test_trajectories: 100  # null for all
  significance_level: 0.05

# Model architecture (placeholders for actual model configs)
models:
  surrogate:
    hidden_dims: [256, 128, 64]
    activation: "relu"
    use_layer_norm: true
    dropout_rate: 0.1
  
  acquisition:
    hidden_dims: [128, 64]
    activation: "relu"
    use_layer_norm: true
    dropout_rate: 0.1

# Logging configuration
logging:
  level: "INFO"
  log_file: "logs/behavioral_cloning.log"
  use_wandb: true
  wandb_project: "causal-bayes-opt-bc"
  run_name: "bc_training_dev"

# Output configuration
output:
  results_directory: "results/behavioral_cloning/dev"
  checkpoint_dir: "checkpoints/behavioral_cloning/dev"
  save_checkpoints: true
  checkpoint_frequency: 10  # epochs

# Compute configuration
compute:
  device: "auto"  # auto, cpu, gpu
  memory_limit_gb: null  # null for no limit
  num_workers: 4  # for data loading

# Experimental features
experimental:
  use_mixed_precision: false
  gradient_clipping: 1.0
  weight_decay: 1e-4