# @package training
# Base GRPO training configuration

algorithm:
  learning_rate: 0.0001
  batch_size: 64
  entropy_coefficient: 0.01
  value_loss_coefficient: 0.5
  clip_ratio: 0.2
  max_grad_norm: 0.5

experience:
  buffer_size: 10000
  prioritized_replay: false
  min_experiences_before_training: 100

curriculum:
  enabled: false
  num_stages: 3
  progression_threshold: 0.8

optimization:
  warmup_steps: 50
  eval_frequency: 100
  checkpoint_frequency: 500
