# @package _global_
# Joint Training Configuration

training:
  # Training parameters
  n_training_steps: 50
  learning_rate: 0.0001  # Lower LR for joint training
  surrogate_learning_rate: 0.00005  # Even lower for surrogate fine-tuning
  
  # Joint training strategy
  strategy:
    mode: "alternating"  # "alternating", "simultaneous", "progressive"
    surrogate_update_frequency: 3  # Update surrogate every N acquisition updates
    progressive_unfreezing: true
    unfreezing_schedule: [10, 25, 40]
  
  # Training coordination
  coordination:
    warm_up_steps: 10  # Steps before joint updates begin
    stabilization_steps: 5  # Steps to stabilize after unfreezing
  
  # Performance monitoring
  monitoring:
    validate_improvement_frequency: 10
    minimum_improvement_threshold: 0.01
    patience_steps: 20

# Override default checkpointing for joint training
checkpointing:
  save_frequency: 10
  checkpoint_dir: "${paths.checkpoint_base_dir}/joint"

# Override default curriculum thresholds for joint training
curriculum:
  advancement_thresholds:
    combined_performance: 0.7
    stability_metric: 0.9