# @package _global_
# Surrogate Training Configuration

training:
  # Training parameters
  n_training_steps: 1000
  learning_rate: 0.0003
  batch_size: 32
  validation_split: 0.2
  
  # Expert demonstration settings
  demonstrations:
    min_per_difficulty: 100
    max_per_difficulty: 1000
    preprocessing:
      normalize_trajectories: true
      filter_low_quality: true
      quality_threshold: 0.7
  
  # Model architecture
  model:
    complexity: "full"  # "simple", "medium", "full"
    use_continuous: true
    performance_mode: "balanced"  # "fast", "balanced", "quality"
  
  # Training optimization
  optimizer:
    type: "adam"
    weight_decay: 0.0001
    gradient_clipping: 1.0
    early_stopping_patience: 50

# Override default checkpointing for surrogate
checkpointing:
  save_frequency: 100
  checkpoint_dir: "${paths.checkpoint_base_dir}/surrogate"

# Override default curriculum thresholds for surrogate
curriculum:
  advancement_thresholds:
    validation_accuracy: 0.8
    convergence_stability: 0.95