# ACBO Comparison Experiment Configuration
# @package _global_

defaults:
  - training: grpo_base
  - logging: wandb_enabled
  - experiment: acbo_comparison
  - _self_

# Global settings
seed: 42
max_steps: 1000
project_name: "causal_bayes_opt"

# Override for comparison experiment
logging:
  wandb:
    enabled: true
    project: "acbo_comparison"
    entity: null
    tags: ["acbo", "comparison", "causal_discovery"]
    group: "active_vs_surrogate"

# Experiment specific
n_runs: 3
n_scms: 2

# Hydra settings for this experiment
hydra:
  run:
    dir: outputs/acbo_comparison/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: multirun/acbo_comparison/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra:job.num}
