# Quick test configuration for validating setup
# @package _global_

defaults:
  - acbo_comparison_config
  - _self_

# Override for quick testing
experiment:
  environment:
    num_variables: 4      # Small graph for fast testing
  target:
    max_interventions: 5  # Few interventions for speed
  problem:
    edge_density: 0.3

n_runs: 1                 # Single run for testing
n_scms: 1                 # Single SCM for testing

logging:
  wandb:
    enabled: false        # Disable WandB for quick test
    project: "acbo_test"

# Hydra test output
hydra:
  run:
    dir: test_outputs
