# Main Hydra Configuration for Causal Bayesian Optimization Training
# This replaces the 4 separate config systems with a unified Hydra approach

defaults:
  - training: acquisition  # Default to acquisition training
  - experiment: quick_start
  - model: enhanced
  - hydra/launcher: local
  - _self_

# Global settings
seed: 42
device: auto  # "cpu", "gpu", "auto"
precision: float32  # "float16", "float32", "float64"

# Paths
paths:
  base_dir: "."
  data_dir: "data"
  checkpoint_base_dir: "checkpoints"
  results_base_dir: "results"
  outputs_dir: "outputs"  # Hydra working directory

# Common curriculum settings
curriculum:
  difficulty_levels:
    - difficulty_1
    - difficulty_2
    - difficulty_3
    - difficulty_4
    - difficulty_5
  
  # Advancement criteria (can be overridden per component)
  advancement_thresholds:
    avg_reward: 0.5
    improvement_rate: 0.1
    stability_metric: 0.9
  
  # Difficulty scaling parameters
  difficulty_scaling:
    difficulty_1:
      n_nodes: [3, 5]
      edge_prob: [0.2, 0.4]
      noise_scale: 0.1
    difficulty_2:
      n_nodes: [5, 8]
      edge_prob: [0.3, 0.5]
      noise_scale: 0.15
    difficulty_3:
      n_nodes: [8, 12]
      edge_prob: [0.4, 0.6]
      noise_scale: 0.2
    difficulty_4:
      n_nodes: [12, 20]
      edge_prob: [0.5, 0.7]
      noise_scale: 0.25
    difficulty_5:
      n_nodes: [20, 30]
      edge_prob: [0.6, 0.8]
      noise_scale: 0.3
  
  progression:
    min_steps_per_difficulty: 20
    max_attempts_per_difficulty: 3
    auto_advancement: true
    manual_advancement_only: false

# Checkpointing
checkpointing:
  enabled: true
  save_frequency: 10
  keep_best_n: 3
  auto_cleanup: true

# Logging
logging:
  level: INFO
  save_intermediate_results: true
  
  # WandB integration
  wandb:
    enabled: false
    project: "causal-bayes-opt"
    entity: null
    tags: []
    group: null
    name: null
    notes: ""
    
# Resource management  
resources:
  max_parallel_training: 1
  gpu_memory_fraction: 0.8
  cpu_cores: 4