python3 graph5_script_unknown.py --seeds_replicate 17 --n_observational 200 --n_trials 50 --n_anchor_points 35 --run_num 1 --noiseless --doubly_robust
python3 graph5_script_unknown.py --seeds_replicate 87 --n_observational 200 --n_trials 50 --n_anchor_points 35 --run_num 2 --noiseless --doubly_robust
python3 graph5_script_unknown.py --seeds_replicate 89 --n_observational 200 --n_trials 50 --n_anchor_points 35 --run_num 3 --noiseless --doubly_robust
python3 graph5_script_unknown.py --seeds_replicate 69 --n_observational 200 --n_trials 50 --n_anchor_points 35 --run_num 4 --noiseless --doubly_robust
python3 graph5_script_unknown.py --seeds_replicate 7 --n_observational 200 --n_trials 50 --n_anchor_points 35 --run_num 5 --noiseless --doubly_robust
python3 graph5_script_unknown.py --seeds_replicate 50 --n_observational 200 --n_trials 50 --n_anchor_points 35 --run_num 6 --noiseless --doubly_robust
python3 graph5_script_unknown.py --seeds_replicate 100 --n_observational 200 --n_trials 50 --n_anchor_points 35 --run_num 7 --noiseless --doubly_robust
python3 graph5_script_unknown.py --seeds_replicate 111 --n_observational 200 --n_trials 50 --n_anchor_points 35 --run_num 8 --noiseless --doubly_robust
python3 graph5_script_unknown.py --seeds_replicate 619 --n_observational 200 --n_trials 50 --n_anchor_points 35 --run_num 9 --noiseless --doubly_robust
python3 graph5_script_unknown.py --seeds_replicate 77 --n_observational 200 --n_trials 50 --n_anchor_points 35 --run_num 10 --noiseless --doubly_robust
