# Base configuration for the causal-meta-learning-cbo project

# Default configuration for graph generation
graph:
  default_nodes: 10
  default_edge_probability: 0.3
  default_mechanism_type: nonlinear
  default_noise_type: gaussian

# Environment settings
environment:
  noise_level: 0.1
  default_scm_type: additive

# Neural components
neural:
  hidden_dim: 64
  graph_encoder_type: gnn
  learning_rate: 0.001
  batch_size: 32

# Meta-learning settings
meta_learning:
  maml:
    adaptation_steps: 5
    alpha: 0.1
    beta: 0.001

  task_representation:
    embedding_dim: 64

# Optimization settings
optimization:
  acquisition_type: entropy
  num_interventions: 10
  intervention_batch_size: 1

# System settings
system:
  seed: 42
  debug: false
  device: cuda
  log_level: info
