python3 graph4_script.py --seeds_replicate 42 --n_observational 200 --n_trials 30 --n_anchor_points 35 --run_num 1 --noiseless
python3 graph4_script.py --seeds_replicate 11 --n_observational 200 --n_trials 30 --n_anchor_points 35 --run_num 2 --noiseless
python3 graph4_script.py --seeds_replicate 89 --n_observational 200 --n_trials 30 --n_anchor_points 35 --run_num 3 --noiseless
python3 graph4_script.py --seeds_replicate 69 --n_observational 200 --n_trials 30 --n_anchor_points 35 --run_num 4 --noiseless
python3 graph4_script.py --seeds_replicate 17 --n_observational 200 --n_trials 30 --n_anchor_points 35 --run_num 5 --noiseless
python3 graph4_script.py --seeds_replicate 60 --n_observational 200 --n_trials 30 --n_anchor_points 35 --run_num 1 --noiseless
python3 graph4_script.py --seeds_replicate 12 --n_observational 200 --n_trials 30 --n_anchor_points 35 --run_num 2 --noiseless
python3 graph4_script.py --seeds_replicate 19 --n_observational 200 --n_trials 30 --n_anchor_points 35 --run_num 3 --noiseless
python3 graph4_script.py --seeds_replicate 1234 --n_observational 200 --n_trials 30 --n_anchor_points 35 --run_num 4 --noiseless
python3 graph4_script.py --seeds_replicate 4321 --n_observational 200 --n_trials 30 --n_anchor_points 35 --run_num 5 --noiseless